Adding thirdweb Faucet
mode-network/documentation pull request #17
Opened 2024-08-07 22:30 UTC by mikedjshin

Adding thirdweb Mode Sepolia Faucet

2024-08-08 12:23 UTC, fede2442 commented on tools/testnet-faucets.md
> +### [Aori Faucet](https://app.aori.io/faucet)
Please remove this character to leave the rest of the page the same as it was, only adding the new changes.

2024-08-08 12:24 UTC, fede2442 requested changes
Thanks for your submission! 

please remove the extra character mentioned in the comment and it will be approved.

2024-08-08 16:49 UTC, mikedjshin commented
Done!

2024-08-14 03:48 UTC, fede2442 approved these changes

2024-08-14 03:48 UTC, merged